/**
 * @file armEncode.h
 * @brief Covert written instructions into their encoded binary equivalent.
 */
#ifndef ARMENCODE_H
#define ARMENCODE_H

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

class Interconnect;

/**
 * @brief Clean the temp files generated by armEncodeASM()
 *
 * @param tempDir - Directory to delete.
 */
void cleanUpEncodeTemps(std::filesystem::path tempDir = "asm_temp");

/**
 * @brief Converts a string of ARM assembly in the binary encoding. Each line of assembly
 * is an element of the returned array.
 *
 * @param instructions The assembly program to assemble.
 * @param arm7 True if assembling arm7 code, else arm9 is targeted.
 * @return std::vector<uint32_t>
 */
std::vector<uint32_t> armEncodeASM(std::string instructions, bool arm7 = true);

/**
 * @brief Assembles and writes the passed program into emulator's memory.
 *
 * @param program Assembly code to assemble and write.
 * @param startAddress The address to begin writing to.
 * @param bus The bus to write to
 * @param arm7 Boolean indicating which ARM memory map to use. True uses ARM7 and false uses the
 * ARM9.
 */
void writeProgramToMemory(std::string program, uint32_t startAddress, Interconnect* bus, bool arm7);

#endif