/**
 * @file armEncode.h
 * @brief Covert written instructions into their encoded binary equivelent.
 */
#ifndef ARMENCODE_H
#define ARMENCODE_H

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

/**
 * @brief Clean the temp files generated by armEncodeASM()
 *
 * @param tempDir - Directory to delete.
 */
void cleanUpEncodeTemps(std::filesystem::path tempDir = "asm_temp");

/**
 * @brief Converts a string of ARM assembly in the binary encoding. Each line of assembly
 * is an element of the returned array.
 *
 * @param instructions The assembly program to assemble.
 * @return std::vector<uint32_t>
 */
std::vector<uint32_t> armEncodeASM(std::string instructions);

#endif